### ISSUE TITLE
replace ChaCha20Poly1305 implementation

### ISSUE THREAD

**Issue by aead** [brutella/hc#74]
I recommend to switch from my ChaCha20Poly1305 implementation to the "official" [golang](https://godoc.org/golang.org/x/crypto/chacha20poly1305) implementation.
I'm planning to restructure my repository (backward comp. breaking changes) in a few weeks and I don't want to break your build. 
The golang implementation will also lead to a significant performance improvement on amd64 (caused by more specialized code), but will decrease the performance on 386 and probably on arm. But there's work in progress to solve this :smile:

**Comment by aead** [comment]
Sry, you use vendoring - so this has low priority

**Comment by reejinbouk** [comment]
new install for "go get github/brutella/hc" and got this error:

# github.com/brutella/hc/crypto/chacha20poly1305
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:28: undefined: chacha20.NewChaCha20Poly1305
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:29: not enough arguments to return
	have (<T>)
	want ([]byte, error)
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:35: undefined: chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:35: invalid array bound chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:46: undefined: chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:51: undefined: chacha20.NewChaCha20Poly1305


looks like it's used by hc

**Comment by gabrielverani** [comment]
Me to got this error:

github.com/brutella/hc/crypto/chacha20poly1305
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:28: undefined: chacha20.NewChaCha20Poly1305
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:29: not enough arguments to return
have ()
want ([]byte, error)
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:35: undefined: chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:35: invalid array bound chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:46: undefined: chacha20.TagSize
../github.com/brutella/hc/crypto/chacha20poly1305/chacha20_poly1305.go:51: undefined: chacha20.NewChaCha20Poly1305

**Comment by aead** [comment]
@reejinbouk @gabrielverani 
A tmp. workaround:
`cd $GOPATCH/src/github.com/aead/chacha20`
`git checkout -b temp 7e1038a97ad08a9a16cb88ed7a6778b366ba4d99`
This should fix the hc build...
This will checkout the state of my repo before the backward-comp. breaking change, but this is just a temp. solution - this situation must be fixed by the project maintainers...

**Comment by gabrielverani** [comment]
@aead 
Worked with this version and with go 1.7.5, go 1.8 does not work
Thank you

**Comment by brutella** [comment]
@pmaene Do you want to work on this?

**Comment by Pmaene** [comment]
@brutella Yeah, I'll look into this.

**Comment by aead** [comment]
@Pmaene you can either use the offical [golang](https://godoc.org/golang.org/x/crypto/chacha20poly1305) implementation (recommended), or use my (X)ChaCha20Poly1305 [repo](https://godoc.org/github.com/aead/chacha20poly1305)

**Comment by Pmaene** [comment]
@aead Thanks for the tip! I decided to use Go's official implementation (see #78). The API was actually almost identical to the one of your previous implementation, so this was pretty easy to fix.

**Comment by brutella** [comment]
@Pmaene Thanks
